version: '3'
networks:
  banco:
  api:
  redis:
services:
  mongo:
    image: mongo:4.0
    networks:
      - banco
  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - redis
  api-avaliacao:
    image: node:8.9.0
    volumes:
      - ./planetas-api:/planetas-api
    ports:
      - 3000:3000
    environment:
      NODE_ENV: prd
    command: bash -c "cd /planetas-api && npm i && npm start"
    networks:
      - api
      - banco
      - redis
    depends_on:
      - mongo 
      - redis     